package cli

const (
	flagProposalID   = "proposal-id"
	flagTitle        = "title"
	flagDescription  = "description"
	flagProposalType = "type"
	flagDeposit      = "deposit"
	flagVoter        = "voter"
	flagOption       = "option"
	flagDepositor    = "depositor"
	flagStatus       = "status"
	flagNumLimit     = "limit"
	flagParam        = "param"
	flagOp           = "op"
	flagModule       = "module"
	flagKey          = "key"
	flagPath         = "path"
	flagUsage        = "usage"
	flagDestAddress  = "dest-address"
	flagPercent      = "percent"
	flagVersion      = "version"
	flagSoftware     = "software"
	flagSwitchHeight = "switch-height"
	flagThreshold    = "threshold"

	//for addAssetProposal
	flagAssetFamily         = "asset-family"
	flagAssetSymbol         = "asset-symbol"
	flagAssetName           = "asset-name"
	flagAssetDecimal        = "asset-decimal"
	flagAssetSymbolMinAlias = "asset-symbol-min-alias"
	flagAssetInitialSupply  = "asset-initial-supply"
	flagAssetMaxSupply      = "asset-max-supply"
	flagAssetMintable       = "asset-mintable"
)
