package cli

const (
	flagProposalID   = "proposal-id"
	flagTitle        = "title"
	flagDescription  = "description"
	flagProposalType = "type"
	flagDeposit      = "deposit"
	flagVoter        = "voter"
	flagOption       = "option"
	flagDepositor    = "depositor"
	flagStatus       = "status"
	flagNumLimit     = "limit"
	flagParam        = "param"
	flagOp           = "op"
	flagModule       = "module"
	flagKey          = "key"
	flagPath         = "path"
	flagUsage        = "usage"
	flagDestAddress  = "dest-address"
	flagPercent      = "percent"
	flagVersion      = "version"
	flagSoftware     = "software"
	flagSwitchHeight = "switch-height"
	flagThreshold    = "threshold"

	//for addTokenProposal
	flagTokenSymbol         = "token-symbol"
	flagTokenSymbolAtSource = "token-symbol-at-source"
	flagTokenName           = "token-name"
	flagTokenDecimal        = "token-decimal"
	flagTokenSymbolMinAlias = "token-symbol-min-alias"
	flagTokenInitialSupply  = "token-initial-supply"
	flagTokenMaxSupply      = "token-max-supply"
	flagTokenMintable       = "token-mintable"
)
