name: Build and Deploy Docs

on:
  push:
    branches: [ "master" ]
    paths: [ "docs/**" ]

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'docs/'
        sparse-checkout-cone-mode: false

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        file: ./docs/Dockerfile
        push: true
        tags: irisnet/docs:${{ github.sha }}
        
  deploy:
    name: Deploy
    runs-on: default-runner-set
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:      
    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        install_components: "gke-gcloud-auth-plugin"

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENDITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials app --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GKE_PROJECT }}
        kubectl set image -n irisnet deployment/irisnet-docs frontend=irisnet/docs:${{ github.sha }} 
        kubectl rollout status -n irisnet deployment/irisnet-docs
